name: "home-manager build"
on:
  push:
    branches:
    - server-config
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        git clone https://github.com/$GITHUB_REPOSITORY -b server-config ~/.nixpkgs
        cd ~/.nixpkgs && nix-shell --run "rebuild"
